version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: shadys
      POSTGRES_PASSWORD: root
      POSTGRES_DB: check
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data